config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'delivery_addresses/edit'
    get 'delivery_addresses/index'
  end
  #namespace :public do
    #get 'orders/complete'
    #get 'orders/confirm'
    #get 'orders/index'
    #get 'orders/new'
    #get 'orders/show'
  #end
  #namespace :public do
    #get 'cart_items/index'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/unsubscribe'
  #end
  #namespace :public do
    #get 'homes/top'
    #get 'homes/about'
  #end
  #namespace :admin do
    #get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
  #end
  #namespace :admin do
    #get 'items/index'
    #get 'items/new'
    #get 'items/create'
    #get 'items/show'
    #get 'items/edit'
    #get 'items/update'
  #end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

get 'admin' => 'admin/homes#top'

get '/items' => 'public/items#index'

get '/items/:id' => 'public/items#show' , as: 'item'

get '/about' => 'public/homes#about'


  namespace :admin do
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:update]
    resources :orders, only:[:show, :update]
  end

  devise_scope :customer do
    get '/customers', to: 'public/registrations#new'
  end
  get 'customers/mypage' => 'public/customers#show'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  resources :delivery_addresses, module: :public, :except => [:new, :show]
  resources :cart_items, module: :public, :except => [:new, :show, :edit] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, module: :public, :only => [:new,:create,:index,:show] do
    collection do
      post 'confirm'
      get 'complete'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre

  attachment :image
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true, presence:true

  validates :introduction, :price, presence: true
  validates  :sales_status, inclusion: {in: [true, false]}


  # 消費税の計算 roundで小数点の切り上げ
  def add_tax_price
        (self.price * 1.10).round
  end
  #itemがcart_itemの所有者
  has_many :cart_items, dependent: :destroy
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :sales_status, :genre_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container mb-3">
  <div class="row">
    <h2 class="mx-5 mt-5 bg-light px-4 shadow">商品編集</h2>
  </div>
 </div>
  <div class="row justify-content-center bg-color pt-3">
    <%= form_with model: @item, url: admin_item_path,method: :patch, local: true do |f| %>
    <div class="form-group row form-inline">
      <div class="col-auto"><%= f.label :"商品画像", class: "col-form-label"%></div>
      <div class="col-auto"><%= f.attachment_field :image, class: "form-control-file" %></div>
    </div>
    <div class="form-group row form-inline">
      <div class="col-auto"><%= f.label :"商品名", class: 'col-form-label mr-3' %></div>
      <div class="col-auto"><%= f.text_field :name, class: 'form-control' %></div>
    </div>
    <div class="form-group row">
      <div class="col-auto"><%= f.label :"商品説明", class: 'col-form-label' %></div>
      <div class="col-auto"><%= f.text_area :introduction, class: 'form-control' %></div>
    </div>
    <div class="form-group row">
      <div class="col-auto"><%= f.label :"ジャンル", class: 'col-form-label' %></div>
      <div class="col-auto align-self-center"><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "-- 選択して下さい --", class: 'form-control' %></div>
    </div>
    <div class="form-group row form-inline">
      <div class="col-auto"><%= f.label :"税抜価格", class: 'col-form-label' %></div>
      <div class="col-auto align-middle"><%= f.text_field :price, class: 'form-control' %></div>
    </div>
    <div class="form-group row form-check-inline">
      <div class="col-auto"><%= f.label :"販売ステータス", class: 'col-form-label' %></div>
      <div class="col-auto form-check-inline">
         <%= f.radio_button :sales_status, true, class: 'form-check-input' %>
         <%= f.label :"販売中", class: 'form-check-label' %>
         <%= f.radio_button :sales_status, false, class: 'form-check-input' %>
         <%= f.label :"販売停止中", class: "form-check-label" %>
      </div>
    </div>
    <div class="row">
      <div class="col-auto">
        <%= f.submit "変更する",class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container mb-5">
  <div class="row mr-3 d-flex">
    <h2 class="mx-5 mt-3 px-4 bg-light shadow">商品一覧</h2>
  </div>
  <div class="d-flex justify-content-end">
      <%= link_to "＋", new_admin_item_path, class: "btn mb-3 shadow pulus color: black" %>
  </div>
  <div class="row d-flex justify-content-center">
    <table class="table table-hover shadow">
      <thead class="bg-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id), class: "item-link" %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <% if item.sales_status == true %>
            <th style="color: green">販売中</th>
          <% else %>
            <th style="color: gray">販売停止中</th>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container mb-5">
  <div class="row">
    <h2 class="mx-5 mt-5  px-4 shadow bg-light">商品新規登録</h2>
  </div>

  <div class="row justify-content-center bg-color pt-3">
    <%= form_with model: @item, url: admin_items_path,method: :post, local: true do |f| %>
    <div class="form-group row form-inline">
      <div class="col-auto"><%= f.label :"商品画像", class: "col-form-label"%></div>
      <div class="col-auto"><%= f.attachment_field :image, class: "form-control-file" %></div>
    </div>
    <div class="form-group row form-inline">
      <div class="col-auto"><%= f.label :"商品名", class: 'col-form-label mr-3' %></div>
      <div class="col-auto"><%= f.text_field :name, class: 'form-control' %></div>
    </div>
    <div class="form-group row">
      <div class="col-auto"><%= f.label :"商品説明", class: 'col-form-label' %></div>
      <div class="col-auto"><%= f.text_area :introduction, class: 'form-control' %></div>
    </div>
    <div class="form-group row form-inline">
      <div class="col-auto"><%= f.label :"ジャンル", class: 'col-form-label' %></div>
      <div class="col-auto align-self-center"><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "-- 選択して下さい --", class: 'form-control' %></div>
    </div>
    <div class="form-group row form-inline">
      <div class="col-auto"><%= f.label :"税抜価格", class: 'col-form-label' %></div>
      <div class="col-auto align-middle"><%= f.text_field :price, class: 'form-control' %></div>
    </div>
    <div class="form-group row form-check-inline">
      <div class="col-auto"><%= f.label :"販売ステータス", class: 'col-form-label' %></div>
      <div class="col-auto form-check-inline">
         <%= f.radio_button :sales_status, true, class: 'form-check-input' %>
         <%= f.label :"販売中", class: 'form-check-label' %>
         <%= f.radio_button :sales_status, false, class: 'form-check-input' %>
         <%= f.label :"販売停止中", class: "form-check-label" %>
      </div>
    </div>
    <div class="row">
      <div class="col-auto">
        <%= f.submit "新規登録",class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container m-5">
  <div class="row mt-5">
    <h2 class="ml-5 px-4 bg-light shadow">商品詳細</h2>
  </div>

  <div class="row mt-5">
    <div class="col">
    <%= attachment_image_tag @item, :image, :fill, 400, 350, format:'jpeg', class: "float-right" %>
    </div>

    <div class="col">
      <table class="table table-borderless">
      　<tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
          　<td>商品説明</td>
          　<td><%= @item.introduction %></td>
          </tr>

          <tr>
          　<td class="text-nowrap">税込価格<br>
              (税抜価格)
          　</td>
          　<!-- to_s(:delimited)は3桁ごとにカンマ区切りで表示してくれるメソッド -->
          　<!-- add_tax_priceメソッドはitem.rbに記述 -->
          　<td><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price %>)円</td>
          </tr>

          <tr>
          　<td class="text-nowrap">販売ステータス</td>
            <% if @item.sales_status == true %>
              <th style="color: green">販売中</th>
            <% else %>
              <th style="color: gray">販売停止中</th>
            <% end %>

          </tr>
        </tbody>
      </table>
    </div>
    </div>
    <div class="row">
      <div class="offset-sm-6 col-6">
    　 <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
    　</div>
    </div>
  </div>
</div>