config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'delivery_addresses/edit'
    get 'delivery_addresses/index'
  end
  #namespace :public do
    #get 'orders/complete'
    #get 'orders/confirm'
    #get 'orders/index'
    #get 'orders/new'
    #get 'orders/show'
  #end
  #namespace :public do
    #get 'cart_items/index'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/unsubscribe'
  #end
  #namespace :public do
    #get 'homes/top'
    #get 'homes/about'
  #end
  #namespace :admin do
    #get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
  #end
  #namespace :admin do
    #get 'items/index'
    #get 'items/new'
    #get 'items/create'
    #get 'items/show'
    #get 'items/edit'
    #get 'items/update'
  #end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

get 'admin' => 'admin/homes#top'

get '/items' => 'public/items#index'

get '/items/:id' => 'public/items#show' , as: 'item'

get '/about' => 'public/homes#about'


  namespace :admin do
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:update]
    resources :orders, only:[:show, :update]
  end

  devise_scope :customer do
    get '/customers', to: 'public/registrations#new'
  end
  get 'customers/mypage' => 'public/customers#show'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  resources :delivery_addresses, module: :public, :except => [:new, :show]
  resources :cart_items, module: :public, :except => [:new, :show, :edit] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, module: :public, :only => [:new,:create,:index,:show] do
    collection do
      post 'confirm'
      get 'complete'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #バリデーションの設定
  validates :last_name, :first_name, :kana_last_name, :kana_first_name,
            :post_code, :address, :telephone, presence: true
  validates :email, uniqueness: true
  has_many :delivery_addresses, dependent: :destroy
  #has_one :cart_items

  #customerがcart_itemの所有者
  has_many :cart_items, dependent: :destroy
  #customerがordersの所有者
  has_many :orders, dependent: :destroy

  def full_my_address
    '〒' + post_code + ' ' + address
  end
  #enum is_deleted: { 有効: false, 退会: true }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    #カスタマー一覧用の情報を取得する
    @customers = Customer.page(params[:page]).reverse_order
  end

  def show
    #カスタマーモデルから一つのデータをみるけてくる（IDを使う）
    @customer = Customer.find(params[:id])
  end

  def edit
    #カスタマーモデルから一つのデータをみるけてくる（IDを使う）
    @customer = Customer.find(params[:id])
  end

  def update
    #カスタマーモデルから一つのデータをみるけてくる（IDを使う）
    @customer = Customer.find(params[:id])
    #取得したデータに対して、フォームから送られてきた情報をもとに更新を行う(customer_paramsを経由)
    if @customer.update(customer_params)
      #成功した場合は管理側の顧客情報詳細画面
      redirect_to admin_customer_path(@customer)
    else
      #失敗した場合は編集画面に滞在する
      render :edit
    end
  end

  #コントローラー内部で処理する必要があるためprivate
  private

  def customer_params
    #テーブル（今回はカスタマー）に対し、フォームから受け取る情報をフィルタリングする。
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :post_code, :address, :telephone, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class='container'>
  <div class="row">
    <h2 class="mt-5 shadow px-4 bg-light"><%= @customer.last_name %> <%= @customer.first_name %> さんの会員情報編集</h2>
  </div>

  <div class='form-group row'>
    <p class='col-md-2 col-form-label'>会員ID</p>
    <div class='col'>
      <p class='form-control-plaintext'><%= @customer.id %></p>
    </div>
  </div>

  <%# モデルにインスタンス変数を指定するだけではコントローラーをうまく認識してくれないため、url・method:のオプションを利用する %>
  <%#url:→どのコントローラーのどのアクションを使うか method:→どのメソッドを使うか%>
  <%= form_with model:@customer, url: admin_customer_path, method: :PATCH, local: true do |f| %>
    <div class='form-group row'>
      <%= f.label '名前', class: 'col-md-2 col-form-label' %>
      <div class='col-auto'>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class='col-auto'>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group row'>
      <%= f.label 'ふりがな', class: 'col-md-2 col-form-label' %>
      <div class='col-auto'>
        <%= f.text_field :kana_last_name, class: 'form-control' %>
      </div>
      <div class='col-auto'>
        <%= f.text_field :kana_first_name, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group row'>
      <%= f.label '郵便番号', class: 'col-md-2 col-form-label' %>
      <div class='col-auto'>
        <%= f.text_field :post_code, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group row'>
      <%= f.label '住所', class: 'col-md-2 col-form-label' %>
      <div class='col'>
        <%= f.text_field :address, class: 'col-md-9 form-control' %>
      </div>
    </div>

    <div class='form-group row'>
      <%= f.label '電話番号', class: 'col-md-2 col-form-label' %>
      <div class='col-auto'>
        <%= f.text_field :telephone, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group row'>
      <%= f.label 'メールアドレス', class: 'col-md-2 col-form-label' %>
      <div class='col-auto'>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group row align-items-center'>
      <%= f.label '会員ステータス', class: 'col-md-2 col-form-label' %>
      <div class='col-auto'>
        <div class='form-check form-check-inline'>
          <%= f.radio_button :is_deleted, :false, class: 'form-check-input' %>
          <%= f.label :is_deleted, '有効', value: false, class:'form-check-label' %>
        </div>
        <div class='form-check form-check-inline'>
          <%= f.radio_button :is_deleted, :true, class: 'form-check-input'  %>
          <%= f.label :is_deleted, '退会', value: true, class:'form-check-label' %>
        </div>
      </div>
    </div>

    <div class='form-group row pb-5'>
      <div class='col-md-2'></div>
      <div class='col'>
        <div class='actions'>
          <%= f.submit '変更を保存', class:'btn btn-success btn-lg col-md-3' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
   <h2 class="mx-5 mt-3 px-4 bg-light shadow">会員一覧</h2>
  </div>

  <div class="row shadow mt-4">
   <table class='table table-hover'>

    <thead class="bg-light">
     <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
     </tr>
    </thead>

   <tbody>

    <% @customers.each do |customer| %>
     <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.last_name + customer.first_name , admin_customer_path(customer) %></td>
      <td><%= customer.email %></td>
      <td>
       <% if customer.is_deleted == true %>
        <p class="col-md-auto text-secondary font-weight-bold">退会</p>
       <% else %>
        <p class="col-md-auto text-success font-weight-bold">有効</p>
       <% end %>
      </td>
     </tr>
    <% end %>
    <%= paginate @customers %>

    </tbody>

   </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container m-5'>
  <div class="row">
    <h2 class="mx-5  px-4 shadow bg-light"><%= @customer.last_name %> <%= @customer.first_name %> さんの会員情報</h2>
  </div>

  <div class='row mt-4 ml-5'>
    <p class='col-md-2'>会員ID</p>
    <p class='col-md-2'><%= @customer.id %></p>
  </div>

  <div class='row ml-5'>
    <p class='col-md-2'>氏名</p>
    <p class='col-md-2'><%= @customer.last_name %> <%= @customer.first_name %></p>
  </div>

  <div class='row ml-5'>
    <p class='col-md-2'>フリガナ</p>
    <p class='col-md-2'><%= @customer.kana_last_name %> <%= @customer.kana_first_name %></p>
  </div>

  <div class='row ml-5'>
    <p class='col-md-2'>郵便番号</p>
    <p class='col-md-2'><%= @customer.post_code %></p>
  </div>

  <div class='row ml-5'>
    <p class='col-md-2'>住所</p>
    <p class='col-md-2'><%= @customer.address %></p>
  </div>

  <div class='row ml-5'>
    <p class='col-md-2'>電話番号</p>
    <p class='col-md-2'><%= @customer.telephone %></p>
  </div>

  <div class='row ml-5'>
    <p class='col-md-2'>メールアドレス</p>
    <p class='col-md-2'><%= @customer.email %></p>
  </div>

  <div class='row ml-5'>
    <p class='col-md-2'>会員ステータス</p>
      <% if @customer.is_deleted == true %>
       <p class="col-md-2 text-secondary font-weight-bold">退会</p>
      <% else %>
       <p class="col-md-2 text-success font-weight-bold">有効</p>
      <% end %>
    </p>
  </div>

  <div class='row mt-1'>
    <p class='col-md-2'></p>
    <p class='col-md-2'><%= link_to '編集する', edit_admin_customer_path(@customer), class: "btn btn-success edit_customer_#{@customer.id}" %></p>
    <p class='col-md-3'><%= link_to '注文履歴一覧を見る', admin_path, class: "btn btn-primary" %></p>
  </div>

</div>