config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'delivery_addresses/edit'
    get 'delivery_addresses/index'
  end
  #namespace :public do
    #get 'orders/complete'
    #get 'orders/confirm'
    #get 'orders/index'
    #get 'orders/new'
    #get 'orders/show'
  #end
  #namespace :public do
    #get 'cart_items/index'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/unsubscribe'
  #end
  #namespace :public do
    #get 'homes/top'
    #get 'homes/about'
  #end
  #namespace :admin do
    #get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
  #end
  #namespace :admin do
    #get 'items/index'
    #get 'items/new'
    #get 'items/create'
    #get 'items/show'
    #get 'items/edit'
    #get 'items/update'
  #end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

get 'admin' => 'admin/homes#top'

get '/items' => 'public/items#index'

get '/items/:id' => 'public/items#show' , as: 'item'

get '/about' => 'public/homes#about'


  namespace :admin do
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:update]
    resources :orders, only:[:show, :update]
  end

  devise_scope :customer do
    get '/customers', to: 'public/registrations#new'
  end
  get 'customers/mypage' => 'public/customers#show'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  resources :delivery_addresses, module: :public, :except => [:new, :show]
  resources :cart_items, module: :public, :except => [:new, :show, :edit] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, module: :public, :only => [:new,:create,:index,:show] do
    collection do
      post 'confirm'
      get 'complete'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  # has_many :products,dependent :destroy
  has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/create.html.erb
<h1>Admins::Genres#create</h1>
<p>Find me in app/views/admins/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<h1>（管理者側）ジャンル編集</h1>
<br></br>

<%#= form_with model: @genre,url: admin_genre_path(@genre),local: true do |f| %>
<%#= f.text_field :name %>
<%#= f.submit '変更を保存', class: "btn btn-success" %>
<%# end %>
<%= form_with model: @genre,url: admin_genre_path(@genre),local: true do |f| %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>ジャンル名</th>
      <th>
        <%= f.text_field :name, autofocus: true %>
      </th>
      <th>
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </th>
    </tr>
  </thead>
</table>
<% end %>

app/views/admin/genres/index.html.erb
  <div class="row mr-3 d-flex">
    <h2 class="mx-5 mt-3 px-4 bg-light shadow">ジャンル一覧・追加</h2>
  </div>
<br></br>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>ジャンル名</th>
        <%= form_with model: @genre,url: admin_genres_path,local: true do |f|%>
      <th>
        <%= f.text_field :name, placeholder: "ジャンル名" %>
      </th>
      <th>
        <%= f.submit '新規登録', class: "btn btn-success" %>
      </th>
        <% end %>
    </tr>
  </thead>

  <thead>
    <tr>
      <td>ジャンル</td>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td>
        <%= link_to "編集する", edit_admin_genre_path(genre.id),class: "btn btn-sm btn-success" %>
      </td>
      <td>
        <%= link_to "削除", admin_genre_path(genre.id),method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: "btn btn-sm btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/genres/update.html.erb
<h1>Admins::Genres#update</h1>
<p>Find me in app/views/admins/genres/update.html.erb</p>