config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'delivery_addresses/edit'
    get 'delivery_addresses/index'
  end
  #namespace :public do
    #get 'orders/complete'
    #get 'orders/confirm'
    #get 'orders/index'
    #get 'orders/new'
    #get 'orders/show'
  #end
  #namespace :public do
    #get 'cart_items/index'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/unsubscribe'
  #end
  #namespace :public do
    #get 'homes/top'
    #get 'homes/about'
  #end
  #namespace :admin do
    #get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
  #end
  #namespace :admin do
    #get 'items/index'
    #get 'items/new'
    #get 'items/create'
    #get 'items/show'
    #get 'items/edit'
    #get 'items/update'
  #end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

get 'admin' => 'admin/homes#top'

get '/items' => 'public/items#index'

get '/items/:id' => 'public/items#show' , as: 'item'

get '/about' => 'public/homes#about'


  namespace :admin do
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:update]
    resources :orders, only:[:show, :update]
  end

  devise_scope :customer do
    get '/customers', to: 'public/registrations#new'
  end
  get 'customers/mypage' => 'public/customers#show'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  resources :delivery_addresses, module: :public, :except => [:new, :show]
  resources :cart_items, module: :public, :except => [:new, :show, :edit] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, module: :public, :only => [:new,:create,:index,:show] do
    collection do
      post 'confirm'
      get 'complete'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #バリデーションの設定
  validates :last_name, :first_name, :kana_last_name, :kana_first_name,
            :post_code, :address, :telephone, presence: true
  validates :email, uniqueness: true
  has_many :delivery_addresses, dependent: :destroy
  #has_one :cart_items

  #customerがcart_itemの所有者
  has_many :cart_items, dependent: :destroy
  #customerがordersの所有者
  has_many :orders, dependent: :destroy

  def full_my_address
    '〒' + post_code + ' ' + address
  end
  #enum is_deleted: { 有効: false, 退会: true }
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
    #バリデーションの追加(郵便番号、住所、宛名のないデータを登録できなくする。)
  validates :post_code, :address, :name, presence: true
  #外部キーの設定(カスタマーへ)
  belongs_to :customer

  #住所をまとめて表示する
  def full_address
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  # has_many :products,dependent :destroy
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre

  attachment :image
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true, presence:true

  validates :introduction, :price, presence: true
  validates  :sales_status, inclusion: {in: [true, false]}


  # 消費税の計算 roundで小数点の切り上げ
  def add_tax_price
        (self.price * 1.10).round
  end
  #itemがcart_itemの所有者
  has_many :cart_items, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  enum order_status: { 入金待ち: 0, 入金確認: 1, 制作中: 2, 発送準備中: 3, 発送済み: 4 }
  enum payment: { クレジットカード: 0, 銀行振込: 1 }
  has_many :order_items, dependent: :destroy

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  def add_tax_price_on_purchase
    (self.price_on_purchase * 1.10).round
  end

  enum production_status: { 着手不可:0, 制作待ち:1, 製作中:2, 制作完了:3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).reverse_order.per(10)
    @sum = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :sales_status, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="background-color:#FFDBC9">

    <!--ロゴ-->

<!--ここで、ディスプレイサイズの指定と背景色の指定-->
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="logo" href="/"><%= image_tag 'header-logo2.jpeg', size: '120x80' %></a>
          　<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            　<span class="navbar-toggler-icon"></span>
          　</button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %><!--adminでログインされている-->
                <li class="px-2"><%= link_to '商品一覧' , admin_items_path %></li>
                <li class="px-2"><%= link_to '会員一覧' , admin_customers_path %></li>
                <li class="px-2"><%= link_to '注文履歴一覧' , admin_path %></li>
                <li class="px-2"><%= link_to 'ジャンル一覧' , admin_genres_path %></li>
                <li class="pl-2"><%= link_to 'ログアウト' , destroy_admin_session_path, method: :delete %></li>
              <% elsif customer_signed_in? %><!--cutomerでログインされている-->
                <b class="welcome-text">ようこそ、<%= current_customer.last_name %>さん！</b>
                <li class="px-2"><%= link_to 'マイページ' , customers_mypage_path %></li>
                <li class="px-2"><%= link_to '商品一覧' , items_path %></li>
                <li class="px-2"><%= link_to 'カート' , cart_items_path %></li>
                <li class="pl-2"><%= link_to 'ログアウト' , destroy_customer_session_path, method: :delete %></li>
              <% else %><!--ログインされていない-->
                <li class="px-2"><%= link_to 'About' , about_path %></li>
                <li class="px-2"><%= link_to '商品一覧' , items_path %></li>
                <li class="px-2"><%= link_to '新規登録' , new_customer_registration_path %></li>
                <li class="pl-2"><%= link_to 'ログイン' , new_customer_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>


    <!--できれば検索窓もつける-->

   </header>

  <main class='mt-5' style="margin-bottom:100px">
    <%= yield %>
  </main>

  <footer class='fixed-bottom'>

    <div class='d-flex flex-column flex-row-reverse'>
    <%= link_to root_path do %>
     <%= image_tag('ft_logo' , size: '187x60' , class: 'float-right mr-5 mt-2')  %>
    <% end %>
    </div>
    <p class='footer float-right mr-5'><strong>Copyright © 2022 shuhei Team. All rights reserved.</strong></p>
    </div>
  </footer>
  </body>
</html>